---

- name: install psycopg2
  package:
    name: "{{ psycopg2_packages | default(_psycopg2_packages | distro(vars)) }}"
    state: present
  become: yes
  become_user: root

- include_tasks: cluster_item.yml
  with_items: "{{ postgresql_cluster_clusters }}"
  loop_control:
    loop_var: cluster

- include_tasks: cluster_user_item.yml
  with_items: "{{ postgresql_cluster_clusters | cluster_user_items }}"
  loop_control:
    loop_var: cluster_user_item
    label: "{{ cluster_user_item.user.username }}"

- include_tasks: cluster_db_item.yml
  with_items: "{{ postgresql_cluster_clusters | cluster_db_items }}"
  loop_control:
    loop_var: cluster_db_item
    label: "{{ cluster_db_item.database.name }}"

- include_tasks: cluster_user_perms.yml
  with_items: "{{ postgresql_cluster_clusters | cluster_user_items }}"
  loop_control:
    loop_var: cluster_user_item
    label: "{{ cluster_user_item.user.username }}"
